format_version: 10

pipelines:
  onboarding-service:
    group: upi

    materials:
      git:
        git: https://github.com/Karthikkasani2002/karthik.git
        branch: main

    stages:

    - build:
        jobs:
          compile:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      cd onboarding-initiator
                      go build -o app ./cmd/service

    - docker-build:
        jobs:
          docker:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      cd onboarding-initiator
                      docker build -t karthik1209/onboarding:v1 -f deployments/Dockerfile .

    - docker-push:
        jobs:
          push:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      docker push karthik1209/onboarding:v1

    - deploy:
        jobs:
          k8s-deploy:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      kubectl apply -f onboarding-initiator/deployments/k8s/
