format_version: 10

pipelines:
  onboarding-service:
    group: upi

    materials:
      git:
        git: https://github.com/Karthikkasani2002/karthik.git
        branch: main

    stages:

    - build:
        jobs:
          compile:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      cd onboarding-initiator
                      go build -o app ./cmd/service

    - image-build-and-push:
        jobs:
          kaniko:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      /kaniko/executor \
                        --dockerfile=onboarding-initiator/deployments/Dockerfile \
                        --context=$(pwd)/onboarding-initiator \
                        --destination=karthik1209/onboarding:v8 \
                        --insecure \
                        --skip-tls-verify

    - deploy:
        jobs:
          k8s-deploy:
            tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - |
                      kubectl apply -f onboarding-initiator/deployments/k8s/
