apiVersion: v1
kind: Secret

metadata:
  name: onboarding-secret
  namespace: onboarding

type: Opaque

stringData:

  ############################
  # POSTGRES
  ############################
  POSTGRES_USER: onboarding_app
  POSTGRES_PASSWORD: StrongPostgresPass#2026

  ############################
  # REDIS
  ############################
  REDIS_PASSWORD: StrongRedisPass#2026

  ############################
  # KAFKA
  ############################
  KAFKA_USERNAME: admin
  KAFKA_PASSWORD: AdminStrongPass#2026

  ############################
  # TLS CA CERTS (REAL FIX)
  ############################

