apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:

  name: onboarding

  namespace: monitoring

spec:

  selector:

    matchLabels:

      app: onboarding

  endpoints:

  - port: http

    path: /metrics

    interval: 15s
